---
jobs:
- name: job-publish
  public: true
  serial: true
  plan:
  - get: resource-tutorial
    params:
      build: resource-tutorial/docker
jobs:
- name: job-deploy
  public: true
  serial: true
  plan:
  - get: resource-tutorial
  - put: hello-world-docker-image
    params:
      manifest: resource-tutorial/manifest/manifest.yml
      path: resource-tutorial
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/dhaneshande/build_docker_image_pushPCF.git

- name: hello-world-docker-image
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
